apihost: "lab.deepidea.cloud"
replicaCount: 1
imagereposync:
  name: sync-repo
  repository: kupolua/sync-repo
  tag: latest
  pullPolicy: IfNotPresent
imagenginxlua:
  name: nginx-lua
  repository: kupolua/nginx_lua
  tag: latest
  pullPolicy: IfNotPresent
env:
  webuipath: "webui/html"
  gitrepourl: "https://github.com/kupolua/interactive-images.git"
  gitbranch: "react"
  gitreposynctime: ""
service:
  name: webui-port
  type: LoadBalancer
  externalPort: 80
  internalPort: 80
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate
volumes:
  volumename: www-data
  volumepath: /www-data
  configname: config
  configpath: /etc/nginx/conf/conf.d
configmap:
  defaultconf: |
    server {
            listen       80;
           server_name  localhost;

           location / {
               set_by_lua_block $webui_path { return os.getenv("WEBUI_PATH") }

               root   /www-data/$webui_path;
               index  index.html index.htm;
           }
        }
restartPolicy: Always