apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: {{ .Values.apihost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
              servicePort: 80
            path: /